@RootPath = https://localhost:7297
@JwtToken = tbd

###

GET {{RootPath}}/api/demo/
Accept: application/json
Authorization: Bearer {{JwtToken}}

###

POST {{RootPath}}/api/auth/token
Content-Type: application/json

{
  "username": "demo",
  "password": "demo"
}