<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>DustInTheWind.$(MSBuildProjectName)</AssemblyName>
		<RootNamespace>DustInTheWind.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.16" />
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\AspNetCoreAuthenticationDemo.Security\AspNetCoreAuthenticationDemo.Security.csproj" />
	</ItemGroup>

</Project>
